apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-sample-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-sample
  template:
    metadata:
      labels:
        app: react-sample
    spec:
      containers:
        - name: react-sample
          image: adharsh04/react-sample:latest
          ports:
            - containerPort: 80
